version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: evol-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=fr-ser-sqlite-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./evol.db:/var/lib/grafana/evol.db:ro
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
