"""Initial schema

Revision ID: e28a53e684d0
Revises: 
Create Date: 2025-12-07 00:21:09.764972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28a53e684d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=True),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('external_ci_id', sa.String(), nullable=True),
    sa.Column('external_device_session_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_runs_kind'), 'runs', ['kind'], unique=False)
    op.create_index(op.f('ix_runs_repo_id'), 'runs', ['repo_id'], unique=False)
    op.create_index(op.f('ix_runs_started_at'), 'runs', ['started_at'], unique=False)
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_table('ci_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('default_branch', sa.String(), nullable=True),
    sa.Column('tag_count', sa.Integer(), nullable=True),
    sa.Column('branch_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('code_metrics',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('total_loc', sa.Integer(), nullable=False),
    sa.Column('loc_by_dir', sa.JSON(), nullable=True),
    sa.Column('loc_by_lang', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('device_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('device_model', sa.String(), nullable=True),
    sa.Column('device_serial', sa.String(), nullable=True),
    sa.Column('interface_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('log_meta',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('has_log', sa.Boolean(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('binary_disasm',
    sa.Column('artifact_id', sa.String(), nullable=False),
    sa.Column('disasm_text', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('tool_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.artifact_id'], ),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_table('signal_streams',
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('device_run_id', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('url_or_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_run_id'], ['device_runs.run_id'], ),
    sa.PrimaryKeyConstraint('signal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal_streams')
    op.drop_table('binary_disasm')
    op.drop_table('log_meta')
    op.drop_table('device_runs')
    op.drop_table('code_metrics')
    op.drop_table('ci_runs')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_runs_started_at'), table_name='runs')
    op.drop_index(op.f('ix_runs_repo_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_kind'), table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
